import {Critical} from '../../../../../Attack';
import {DamageType} from '../../../../../Damage/DamageType';
import {DiceRoll} from '../../../../../Dice';
import {EquipmentName} from '../../../EquipmentName';
import {WeaponPurposeMelee, WeaponPurposeRangedShooting, WeaponPurposeRangedThrowing} from '../../WeaponPurpose';
import {OffensiveWeaponData} from '../OffensiveWeaponData';
import {type MartialWeaponName} from './MartialWeaponName';

export class MartialWeaponCatalog {
	static items: {
		[N in MartialWeaponName]: OffensiveWeaponData<N>;
	} = {
			battleAxe: new OffensiveWeaponData({
				damage: new DiceRoll(1, 8),
				damageType: DamageType.cutting,
				description: '',
				equipmentName: EquipmentName.battleAxe,
				price: 10,
				purposes: new WeaponPurposeMelee(),
				translatedName: 'Machado de Batalha',
				critical: new Critical(20, 3),
			}),
			cutlass: new OffensiveWeaponData({
				damage: new DiceRoll(2, 4),
				damageType: DamageType.cutting,
				description: '',
				equipmentName: EquipmentName.cutlass,
				price: 15,
				purposes: new WeaponPurposeMelee(),
				translatedName: 'Alfanje',
				slots: 2,
				critical: new Critical(18),
			}),
			flail: new OffensiveWeaponData({
				damage: new DiceRoll(1, 8),
				damageType: DamageType.impact,
				description: '',
				equipmentName: EquipmentName.flail,
				price: 8,
				purposes: new WeaponPurposeMelee(),
				translatedName: 'Mangual',
			}),
			foil: new OffensiveWeaponData({
				damage: new DiceRoll(1, 6),
				damageType: DamageType.piercing,
				description: '',
				equipmentName: EquipmentName.foil,
				price: 20,
				purposes: new WeaponPurposeMelee(),
				translatedName: 'Florete',
				critical: new Critical(18),
			}),
			halberd: new OffensiveWeaponData({
				damage: new DiceRoll(1, 10),
				damageType: [DamageType.cutting, DamageType.piercing],
				description: '',
				equipmentName: EquipmentName.halberd,
				price: 15,
				purposes: new WeaponPurposeMelee(),
				translatedName: 'Alabarda',
				critical: new Critical(20, 3),
				slots: 2,
			}),
			handAndaHalfSword: new OffensiveWeaponData({
				damage: new DiceRoll(2, 6),
				damageType: DamageType.cutting,
				description: '',
				equipmentName: EquipmentName.handAndaHalfSword,
				price: 50,
				purposes: new WeaponPurposeMelee(),
				translatedName: 'Montante',
				critical: new Critical(19),
				slots: 2,
			}),
			hatchet: new OffensiveWeaponData({
				damage: new DiceRoll(1, 6),
				damageType: DamageType.cutting,
				description: '',
				equipmentName: EquipmentName.hatchet,
				price: 6,
				purposes: [
					new WeaponPurposeMelee(),
					new WeaponPurposeRangedThrowing({
						range: 'short',
					}),
				],
				translatedName: 'Machadinha',
				critical: new Critical(20, 3),
			}),
			heavyCrossbow: new OffensiveWeaponData({
				damage: new DiceRoll(1, 12),
				damageType: DamageType.piercing,
				description: '',
				equipmentName: EquipmentName.heavyCrossbow,
				price: 50,
				purposes: new WeaponPurposeRangedShooting({
					range: 'medium',
				}),
				translatedName: 'Besta Pesada',
				critical: new Critical(19),
				slots: 2,
			}),
			longBow: new OffensiveWeaponData({
				damage: new DiceRoll(1, 8),
				damageType: DamageType.piercing,
				description: '',
				equipmentName: EquipmentName.longBow,
				price: 50,
				purposes: new WeaponPurposeRangedShooting({
					range: 'medium',
					damageAttribute: 'strength',
				}),
				translatedName: 'Arco Longo',
				critical: new Critical(20, 3),
				slots: 2,
			}),
			longSword: new OffensiveWeaponData({
				damage: new DiceRoll(1, 8),
				damageType: DamageType.cutting,
				description: '',
				equipmentName: EquipmentName.longSword,
				price: 15,
				purposes: new WeaponPurposeMelee(),
				translatedName: 'Espada Longa',
				critical: new Critical(19),
			}),
			mountedSpear: new OffensiveWeaponData({
				damage: new DiceRoll(1, 8),
				damageType: DamageType.piercing,
				description: '',
				equipmentName: EquipmentName.mountedSpear,
				price: 10,
				purposes: new WeaponPurposeMelee(),
				translatedName: 'Lança Montada',
				critical: new Critical(20, 3),
				slots: 2,
			}),
			pickaxe: new OffensiveWeaponData({
				damage: new DiceRoll(1, 6),
				damageType: DamageType.piercing,
				description: '',
				equipmentName: EquipmentName.pickaxe,
				price: 8,
				purposes: new WeaponPurposeMelee(),
				translatedName: 'Picareta',
				critical: new Critical(20, 4),
			}),
			scimitar: new OffensiveWeaponData({
				damage: new DiceRoll(1, 6),
				damageType: DamageType.cutting,
				description: '',
				equipmentName: EquipmentName.scimitar,
				price: 15,
				purposes: new WeaponPurposeMelee(),
				translatedName: 'Cimitarra',
				critical: new Critical(18),
			}),
			scythe: new OffensiveWeaponData({
				damage: new DiceRoll(2, 4),
				damageType: DamageType.cutting,
				description: '',
				equipmentName: EquipmentName.scythe,
				price: 18,
				purposes: new WeaponPurposeMelee(),
				translatedName: 'Gadanho',
				critical: new Critical(20, 4),
				slots: 2,
			}),
			trident: new OffensiveWeaponData({
				damage: new DiceRoll(1, 8),
				damageType: DamageType.piercing,
				description: '',
				equipmentName: EquipmentName.trident,
				price: 15,
				purposes: [
					new WeaponPurposeMelee(),
					new WeaponPurposeRangedThrowing({
						range: 'short',
					}),
				],
				translatedName: 'Tridente',
			}),
			warAxe: new OffensiveWeaponData({
				damage: new DiceRoll(1, 12),
				damageType: DamageType.cutting,
				description: '',
				equipmentName: EquipmentName.warAxe,
				price: 20,
				purposes: new WeaponPurposeMelee(),
				translatedName: 'Machado de Guerra',
				critical: new Critical(20, 3),
				slots: 2,
			}),
			warHammer: new OffensiveWeaponData({
				damage: new DiceRoll(1, 8),
				damageType: DamageType.impact,
				description: '',
				equipmentName: EquipmentName.warHammer,
				price: 12,
				purposes: new WeaponPurposeMelee(),
				translatedName: 'Martelo de Guerra',
				critical: new Critical(20, 3),
			}),
		};
}
