export enum SkillName {
	acrobatics = 'acrobatics',
	athletics = 'athletics',
	animalHandling = 'animalHandling',
	fight = 'fight',
	reflexes = 'reflexes',
	perception = 'perception',
	survival = 'survival',
	fortitude = 'fortitude',
	aim = 'aim',
	animalRide = 'animalRide',
	war = 'war',
	initiative = 'initiative',
	intimidation = 'intimidation',
	craft = 'craft',
}
