export enum EquipmentName {
	sacredSymbol = 'sacredSymbol',
	priestCostume = 'priestCostume',
	hound = 'hound',
	horse = 'horse',
	pony = 'pony',
	trobo = 'trobo',
	backpack = 'backpack',
	sleepingBag = 'sleepingBag',
	travelerCostume = 'travelerCostume',
	dagger = 'dagger',
	longSword = 'longSword',
	leatherArmor = 'leatherArmor',
	studdedLeather = 'studdedLeather',
	brunea = 'brunea',
}
