export enum EquipmentName {
	sacredSymbol = 'sacredSymbol',
	priestCostume = 'priestCostume',
	hound = 'hound',
	horse = 'horse',
	pony = 'pony',
	trobo = 'trobo',
	backpack = 'backpack',
	sleepingBag = 'sleepingBag',
	travelerCostume = 'travelerCostume',
	dagger = 'dagger',
	club = 'club',
	longSword = 'longSword',
	scythe = 'scythe',
	leatherArmor = 'leatherArmor',
	studdedLeather = 'studdedLeather',
	brunea = 'brunea',
	chainMail = 'chainMail',
	fullPlate = 'fullPlate',
	wand = 'wand',
	staff = 'staff',
	horns = 'horns',
}
