export enum RoleAbilityName {
	specialAttack = 'specialAttack',
	warriorPower = 'warriorPower',
	arcanistPath = 'arcanistPath',
	arcanistSpells = 'arcanistSpells',
	arcanistSupernaturalLineage = 'arcanistSupernaturalLineage',
	rage = 'rage',
	audacity = 'audacity',
	inspiration = 'inspiration',
	bardSpells = 'bardSpells',
	preyMark = 'preyMark',
	tracker = 'tracker',
	honourCode = 'honourCode',
	bulwark = 'bulwark',
	clericFaithfulDevote = 'clericFaithfulDevote',
	clericSpells = 'clericSpells',
	druidFaithfulDevote = 'druidFaithfulDevote',
	wildEmpathy = 'wildEmpathy',
	druidSpells = 'druidSpells',
	ingenuity = 'ingenuity',
	prototype = 'prototype',
	sneakAttack = 'sneakAttack',
	specialist = 'specialist',
	fight = 'fight',
	lightningStrike = 'lightningStrike',
}
