export enum RaceAbilityName {
	versatile = 'versatile',
	rockKnowledge = 'rockKnownledge',
	slowAndAlways = 'slowAndAlways',
	hardAsRock = 'hardAsRock',
	heredrimmTradition = 'heredrimmTradition',
	plantsFriend = 'plantsFriend',
	allihannaArmor = 'allihannaArmor',
	wildEmpathy = 'wildEmpathy',
	gloriennGrace = 'gloriennGrace',
	magicBlood = 'magicBlood',
	elvenSenses = 'elvenSenses',
	ingenious = 'ingenious',
	jointer = 'jointer',
	slenderPlage = 'slenderPlage',
	streetRat = 'streetRat',
	sonOfTormenta = 'sonOfTormenta',
	deformity = 'deformity',
	hornes = 'hornes',
	stiffLeather = 'stiffLeather',
	nose = 'nose',
	fearOfHeights = 'fearOfHeights',
	desires = 'desires',
	elementalResistance = 'elementalResistance',
	mysticTattoo = 'mysticTattoo',
}
